name: Build Pull Request
on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build_plugin:
    name: PR - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: windows x64
            os: windows-latest

          - name: windows arm64ec
            os: windows-latest
            cmakeConfig: -G"Visual Studio 17 2022" -A arm64ec -DCMAKE_SYSTEM_VERSION=10

          - name: macOS
            os: macos-latest
            cmakeConfig: -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

          - name: Linux
            os: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare for JUCE
        uses: surge-synthesizer/sst-githubactions/prepare-for-juce@main
        with:
          os: ${{ runner.os }}

      - name: Build pull request version
        run: |
          cmake -S . -B ./build ${{ matrix.cmakeConfig }} -DCMAKE_BUILD_TYPE=Debug -DJI_LATTICE_COPY_AFTER_BUILD=FALSE
          cmake --build ./build --config Debug --target ji-lattice-plugin-installer --parallel 3

  build_plugin_lindoc:
    name: PR - U20 Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build in Docker
        uses: surge-synthesizer/sst-githubactions/cmake-in-docker@main
        with:
          image: ghcr.io/surge-synthesizer/sst-dockerimages/ubuntu20_gcc11:main
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          cmakeArgs: -DCMAKE_BUILD_TYPE=Debug -GNinja -DJI_LATTICE_COPY_AFTER_BUILD=FALSE
          target: ji-lattice-plugin-installer

      - name: Confirm Build
        run: |
          ls -l build/
